### ISSUE TITLE
ops — a type-corrupted baseline block crashes the bless guard instead of refusing

### ISSUE THREAD

**Issue by dudarenok-maker** [dudarenok-maker/Castwright#2061]
## What

Two small robustness gaps in the golden bless guard, both surfaced by the independent post-merge review of PR #2045. Neither is currently reachable on the committed baseline; both are the same corruption class the guard's *other* branches were deliberately hardened against.

### 1. A type-corrupted baseline block crashes instead of refusing

`server/tts-sidecar/tests/golden/compare.py:353` — `_flatten_leaves(existing)` calls `.items()` with no type guard.

Before PR #2045 the check was `existing == computed`, which cleanly refused for any non-dict `existing`. Reproduced against both shapes:

```
existing = -21.16   -> AttributeError: 'float' object has no attribute 'items'
existing = [1, 2]   -> AttributeError: 'list' object has no attribute 'items'
```

So a hand-resolved merge conflict that collapses `"loudness_dbfs"` to a scalar now aborts the bless with a traceback instead of printing the `GOLDEN_REBLESS_THRESHOLDS` refusal the guard exists to print.

It still fails **closed** — no write happens — so this is an error-quality regression rather than a hole. But the `existing is None` / dropped-key branch immediately above it was hardened for exactly this class of corruption (#2003), so the inconsistency is worth closing.

**Suggested fix:** in `_leaf_diffs`, treat a non-dict on either side as `inf`, which routes it to the normal refusal path.

### 2. `test_live_instruct_golden`'s unblessed-SKIP can `KeyError` instead of skipping

`server/tts-sidecar/tests/golden/test_instruct_golden.py` — the skip guard at `:317` checks `identity`, but `:323` reads `baseline["tolerances"]` unguarded.

A baseline carrying `identity` but no `tolerances` — again the hand-resolved-merge-conflict shape — raises `KeyError` rather than taking the documented SKIP path. Pre-existing, not introduced by #2045.

## Why filed rather than fixed in passing

Both sit in the same functions as PR #2045's fix-forward work, but neither is a defect that fix is addressing, and the `_leaf_diffs` change in particular has a decision in it: whether a non-dict should refuse (treat as `inf`) or be reported as a distinct "corrupted baseline" error with its own message. The second is arguably better UX and is a different code path.

## Acceptance

- A non-dict `existing` or `computed` block produces the guard's normal refusal message (or a dedicated corruption message), not an `AttributeError` traceback.
- An `identity`-present / `tolerances`-absent baseline takes the SKIP path rather than raising `KeyError`.
- Regression tests for both shapes.

## Key files

- `server/tts-sidecar/tests/golden/compare.py` (`_flatten_leaves`, `_leaf_diffs`, `bless_guard_thresholds`)
- `server/tts-sidecar/tests/golden/test_instruct_golden.py` (`test_live_instruct_golden`, `:317`, `:323`)

## Benefit

**Technical** — the bless guard reports every corruption shape the same legible way, instead of one class printing a Python traceback.

Found by independent post-merge review of PR #2045. Refs #2003, #2035, #2042.

**Comment by dudarenok-maker** [comment]
Scheduled into **Round 2, Lane 1** of the v1.15 bug & chore sweep (branch `chore/sidecar-golden-flag-split`), alongside #2060, #2061, #2062 and #2069 — all four sit in the same ~40 lines of `compare.py` and cannot be worked separately.

The design calls each of these issues deferred have been made up front. **The implementation brief is [on #2060](https://github.com/dudarenok-maker/Castwright/issues/2060#issuecomment-5186272882)** — read it before this issue's own "why filed rather than fixed" section, which lists options that are in some cases no longer the ones being taken. This issue's **Acceptance** section stays canonical.

Refs #2042.
