### ISSUE TITLE
Stop during a Coqui render reports a 2s timeout, then unloads anyway

### ISSUE THREAD

**Issue by dudarenok-maker** [dudarenok-maker/Castwright#1921]
Introduced by #1894, deliberately and with eyes open — filed so the trade is tracked rather than discovered.

## What changed

`CoquiEngine.unload()` now acquires `_synth_lock` before dropping the model. That is the fix for a real crash: previously `unload()` nulled `_tts` with no lock while `synthesize()` was dereferencing it, so **pressing Stop mid-chapter could kill the chapter being rendered** with `AttributeError: 'NoneType' object has no attribute 'tts'`.

The cost is that `unload()` now waits for any in-flight forward — tens of seconds to minutes for a long sentence.

## The symptom

`POST /api/sidecar/unload` on the Node side runs under `PROBE_TIMEOUT_MS = 2_000` (`server/src/routes/sidecar-health.ts`). So during an active Coqui render:

1. The user presses **Stop** on the Coqui pill.
2. The sidecar's `/unload` awaits `to_thread(coqui.unload)`, which blocks on `_synth_lock`.
3. Node aborts at 2 s → `503 "Sidecar /unload did not respond within 2000ms"`.
4. The UI reports the Stop as failed.
5. The forward finishes; the unload proceeds; the model is gone a minute later.

So the user sees an error, and then the thing they asked for happens anyway, silently.

The same route serves the Analysing screen's "Load analyzer" auto-evict of the TTS model, so that path can report a spurious failure during any Coqui render too.

## Why it is still an improvement

A 503 on the Stop control is strictly better than a killed chapter. The previous behaviour looked like it worked and destroyed a render. This one looks like it failed and completes correctly.

But the failure is currently *undeclared*: nothing tells the user "the model will stop once the current sentence finishes", and no test covers it.

## Options (not decided)

- Have `/unload` return a distinct "queued — will unload after the current forward" response instead of blocking to timeout, and surface that in the UI.
- Raise the probe budget for `/unload` specifically (it is not really a probe).
- Have the sidecar acknowledge immediately and unload asynchronously.

## Acceptance

- Pressing Stop during an active Coqui render produces an accurate, non-alarming UI result.
- The chapter still completes — the #1894 crash fix must not regress.
- Whatever the mechanism, the analyzer auto-evict path reports honestly too.

## Where it will first be observed

On-box acceptance row **A20** in `docs/testing/onbox-acceptance-register.md` now asks the tester to record what the Stop control reports during a render, precisely so this surfaces on real hardware.

## Key files

- `server/src/routes/sidecar-health.ts` — the `/api/sidecar/unload` handler and `PROBE_TIMEOUT_MS`
- `server/tts-sidecar/main.py` — `CoquiEngine.unload`, the `POST /unload` route
