### ISSUE TITLE
side-XX — unguarded self._base17 derefs bypass #1975's typed error with an AttributeError

### ISSUE THREAD

**Issue by dudarenok-maker** [dudarenok-maker/Castwright#2022]
## Summary

`QwenEngine` dereferences `self._base17` without a `None` check, **outside `_synth_lock`**, at two places. The exact `unload_base17()` that PR #2019 (#1975) hardens against reaches these first, producing an `AttributeError` instead of the clear `RuntimeError` #1975 added.

## Sites

| `main.py` | Deref | Context |
|---|---|---|
| `:6056` | `self._base17.device` | `_load_voice_prompt_17b` |
| `:6057` | `self._base17.model.speech_tokenizer` | same |
| `:6060` | `self._base17.create_voice_clone_prompt` | same |
| `:5853-5859` | same shape | `mint_variant` |

Line numbers verified at `0a856e53`; re-locate by shape.

## Why it matters

`_load_voice_prompt_17b` runs in the window between the pre-existing 1.7B pre-ensure (`main.py:6343`) and the one #1975 added before the lock (`main.py:6384`). A concurrent `POST /unload {model:'1.7b'}` landing there yields:

```
'NoneType' object has no attribute 'device'
```

— and it gets there **before** reaching #1975's new guard at `main.py:6387`, so the clear, actionable message that PR added is bypassed on this path. The user sees an opaque `AttributeError` instead of "Qwen 1.7B-Base model was unloaded before this batch render started — reload it and retry."

Pre-existing, not introduced by #2019, and directly adjacent to its diff. It did not clear that PR's fix-now bar because it needs a re-ensure-vs-raise decision rather than having one obviously-correct answer.

## Fix shape

Capture `self._base17` into a local once at the top of `_load_voice_prompt_17b` and raise the same shaped `RuntimeError` if it is `None` — matching the message style #1975 established — or re-ensure, if that is judged better for this path. Same for the `mint_variant` occurrence. Paired mutation-verified test: null `_base17` between the pre-ensure and the call, assert the typed error rather than an `AttributeError`.

## Related

There is a second, cosmetic inconsistency worth folding in while here: `_guarded_base_synth`'s existing raise at `main.py:6137` uses `f"Qwen {base_attr} model…"`, which leaks the raw attribute name to the user as "Qwen _base model…". #1975's three new messages name the model properly ("Qwen Base", "Qwen 1.7B-Base"), so this older one is now the outlier.

Refs #1975.
