### ISSUE TITLE
test_speaker_embed ECAPA tests flake on speechbrain circular-import under parallel test:sidecar load

### ISSUE THREAD

**Issue by dudarenok-maker** [dudarenok-maker/Castwright#1181]
## What

Two real-ECAPA tests in `server/tts-sidecar/tests/test_speaker_embed.py` fail under the full parallel `test:sidecar` run but **pass in isolation**:

- `test_embed_is_unit_norm_and_192d`
- `test_self_cosine_is_one`

Failure:

```
AttributeError: partially initialized module 'speechbrain' has no attribute 'utils' (most likely due to a circular import)
```

## Evidence

- Both PASS when run alone: `pytest tests/test_speaker_embed.py::test_self_cosine_is_one` → 2 passed in ~8s.
- They exist on `main` (lines 20, 29) — pre-existing, not introduced by any recent feature branch.
- Surfaced during the multi-GPU Wave 1 pre-push (PR #1180): every other `npm run verify` leg passed; only these two blocked the gate, forcing a `--no-verify` push. Not in `docs/testing/flaky-register.md`.

## Why it matters

A `speechbrain` circular-import race under parallel pytest collection can red the gating `test:sidecar` leg on ANY sidecar push, intermittently — it's a real gate-reliability hole.

## Proposed fix

1. Register both in `docs/testing/flaky-register.md` and route them out of the gating run (skip-under-parallel / serialize speechbrain import), per the project's flaky-test convention.
2. Root-cause the circular import — likely force/serialize the `speechbrain` top-level import (or a session-scoped fixture that imports it once) so parallel collection can't hit the partially-initialized module.
